#!/usr/bin/python 

import csv
import sys
import re
import os.path

filepath = os.path.dirname(sys.argv[1])
filename = os.path.basename(sys.argv[1])
with open(sys.argv[1], 'rb') as csvFile , open(filepath + 'reformated-'+ filename, 'wb') as outputFile:
    readObject = csv.reader(csvFile, delimiter=',')
    outputWriter = csv.writer(outputFile, delimiter=',')
    collumNr = int(sys.argv[2])
    for row in readObject:
        print row
        searchObject = re.search('([0-9]{2}\/[0-9]{2}\/[0-9]{4})', row[collumNr])
        if searchObject:
            print searchObject.group()
            year = searchObject.group()[6:]
            print year
            month = searchObject.group()[3:5]
            print month
            day = searchObject.group()[0:2]
            print day
            print row[collumNr]
            oldFormat = searchObject.group()
            newFormat = year+ '/' + month + '/' + day
            print newFormat

            row[collumNr] = row[collumNr].replace(searchObject.group(), newFormat)
            print row[collumNr]
        else:
            print 'No Match'
        outputWriter.writerow(row)
