#!/usr/bin/python 

import csv
import sys
import re
import os.path

filepath = os.path.dirname(sys.argv[1])
filename = os.path.basename(sys.argv[1])
with open(sys.argv[1], 'rb') as csvFile , open(filepath + '/reformated-'+ filename, 'wb') as outputFile:
    readObject = csv.reader(csvFile, delimiter=',')
    outputWriter = csv.writer(outputFile, delimiter=',')
    collumNr = int(sys.argv[2])
    for row in readObject:
        print row
        searchObject = re.search('([0-9]{1,2}\/[0-9]{1,2}\/[0-9]{4})', row[collumNr])
        if searchObject:
            try:
                int(searchObject.group()[1])
                day = searchObject.group()[0:2]
                try:
                    int(searchObject.group()[4])
                    month = searchObject.group()[3:5]
                    year = searchObject.group()[6:]
                except:
                    month = searchObject.group()[3:4]
                    year = searchObject.group()[5:]
            except:
                day = searchObject.group()[0:1]
                try:
                    int(searchObject.group()[3])
                    month = searchObject.group()[2:4]
                    year = searchObject.group()[5:]
                except:
                    month = searchObject.group()[2:3]
                    year = searchObject.group()[4:]
            print searchObject.group()
            print year
            if int(month) < 10:
                month = '0'+ month
            print month
            if int(day) < 10:
                day = '0' + day
            print day
            print row[collumNr]
            oldFormat = searchObject.group()
            newFormat = year+ '/' + month + '/' + day
            print newFormat

            row[collumNr] = row[collumNr].replace(searchObject.group(), newFormat)
            print row[collumNr]
        else:
            print 'No Match'
        outputWriter.writerow(row)
